# This file was generated by GoReleaser. DO NOT EDIT.
class Gocli < Formula
  desc ""
  homepage ""
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dworznik/gocli/releases/download/v0.4.0/gocli_0.4.0_Darwin_x86_64.tar.gz"
    sha256 "455a21a436ebb852f6e4ebb0d4c52ae97fe0b0002c97f9bcfca2672fa57c3200"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dworznik/gocli/releases/download/v0.4.0/gocli_0.4.0_Linux_x86_64.tar.gz"
      sha256 "0b5c3fc6258943f19dc734f113f8d3d11c5cae1558c0676ecc5ea58843e17a1a"
    end
  end

  def install
    bin.install "gocli"
  end
end
